cameras:
  front:
    input:
      url: rtsp://192.168.1.142/11
    output-live:
      format: hls
      url: front.m3u8
      options:
        hls_flags: delete_segments+append_list
        hls_time: 5
        hls_list_size: 5
        hls_base_url: segments/
        hls_segment_filename: segments/front-%d.ts
    basic-detect:
      # coeffs: [1, 1, 1] # Y U V
      threshold: 10 # pixel count normalized
      thumbnail: front/event-%Y-%m-%d-%H-%M-%S.jpg # strftime
      output-url: front/event-%Y-%m-%d-%H-%M-%S.mkv # strftime, no transcode
